#include "mark.h"
/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

char *strcpy(char *dest, char const *source) {
  char *ptr;
  char *tmp;
  char const *tmp___0;

  {
    ptr = dest;
    while ((int const) * source != 0) {
      tmp = ptr;
      ptr++;
      tmp___0 = source;
      source++;
      *tmp = *tmp___0;
    }
    return (dest);
  }
}
