#include "mark.h"
/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

char *strcpy(char *dest, char const *source) {
  MARK(1, 5);
  char *ptr;
  char *tmp;
  char const *tmp___0;

  {
    ptr = dest;
    while ((MARK(1, 4), (int const) * source != 0)) {
      (mark(1, 3), tmp = ptr);
      ptr++;
      tmp___0 = source;
      source++;
      *tmp = *tmp___0;
    }
    return (MARK(1, 1), (dest));
  }
}
