#include "mark.h"
/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

struct bar {
  unsigned int us;
};
void foo(struct bar *b) {

  { return; }
}
void annot_foo(struct bar *b) {

  { return; }
}
void annot_bar(struct bar *b) {

  { return; }
}
