#include "mark.h"
/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

struct bar {
  unsigned int us;
};
void foo(struct bar *b) {

  {
    MARK(1, 2);
    MARK(1, 1);
    return;
  }
}
void annot_foo(struct bar *b) {

  {
    MARK(2, 2);
    MARK(2, 1);
    return;
  }
}
void annot_bar(struct bar *b) {

  {
    MARK(3, 2);
    MARK(3, 1);
    return;
  }
}
