/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

typedef unsigned long uintptr_t;
struct bar {
   unsigned int us ;
};
extern void pgklee_hard_assume(uintptr_t condition ) ;
char buffer[10]  ;
void annot_foo1(int index ) ;
char foo1(int index ) 
{ 
  char result ;

  {
  annot_foo1(index);
  result = buffer[index];
  return (result);
}
}
void annot_foo1(int index ) 
{ 


  {
  pgklee_hard_assume(index >= 0);
  pgklee_hard_assume(index < 10);
  return;
}
}
void foo2(struct bar *b ) 
{ 


  {
  return;
}
}
void annot_foo2(struct bar *b ) 
{ 


  {
  return;
}
}
void annot_bar(struct bar *b ) 
{ 


  {
  return;
}
}
