#include "mark.h"
/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

int main(int argc, char **argv) {
  MARK(1, 6);
  int result;

  {
    result = 0;
    if (argc == 1) {
      (mark(1, 5), result = 10);
    } else if ((mark(1, 4), argc == 2)) {
      (mark(1, 3), result = 50);
    } else {
      (mark(1, 2), result = 51);
    }
    return (MARK(1, 1), (result));
  }
}
