#include "mark.h"
/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

int main(int argc, char **argv) {
  int result;

  {
    result = 0;
    if (argc == 1) {
      result = 10;
    } else if (argc == 2) {
      result = 50;
    } else {
      result = 51;
    }
    return (result);
  }
}
