#include "mark.h"
/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

int main(int argc, char **argv) {
  float f;

  {
    f = 1.0;
    if ((double)f > 2.0) {
      {
        int result_0e4eae1745 = (0);
        return (result_0e4eae1745);
      };
    } else {
      {
        int result_3229cca6e9 = (1);
        return (result_3229cca6e9);
      };
    }
  }
}
