/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is true */

int main(int argc , char **argv ) 
{ 
  float f ;

  {
  f = 1.0;
  if ((double )f > 2.0) {
    return (0);
  } else {
    return (1);
  }
}
}
